name: php-8.1-couch-mongo-publish
on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kirschbaumdevelopment/laravel-test-runner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8.1-couch-mongo
        tags: "8.1-couch-mongo"

  validate:
    runs-on: ubuntu-latest
    needs: publish
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1-couch-mongo

    steps:
      - uses: actions/checkout@v2
      - run: |
        curl -fsSL https://goss.rocks/install | GOSS_VER=v${GOSS_VERSION} sh
        goss --gossfile 8.1-couch-mongo/goss.yaml validate