on: push
name: php-8.2-couch-mongo-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2-couch-mongo

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 8.2-couch-mongo/goss.yaml validate
