on: push
name: php-7.4
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4.0

    steps:
    - uses: actions/checkout@v1

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kirschbaumdevelopment/laravel-test-runner
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7.4
        tags: "7.4"

    - run: goss --gossfile 7.4/goss.yaml validate
