on: push
name: php-8.0-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 8.0/goss.yaml validate
