on: push
name: php-7.3
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3.0

    steps:
    - uses: actions/checkout@v1
    - run: goss validate --gossfile 7.3/goss.yaml
